// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZz-DtWflxkF5w85Ij8JlTyriS_FICi44',
    appId: '1:366242787575:web:368c3de1162a18896b63f2',
    messagingSenderId: '366242787575',
    projectId: 'caretutors-notes-app',
    authDomain: 'caretutors-notes-app.firebaseapp.com',
    storageBucket: 'caretutors-notes-app.firebasestorage.app',
    measurementId: 'G-5H8LW3065S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb4AbeBww_eeSqLSgaetyqqSQOqcLjcsc',
    appId: '1:366242787575:android:0c4901eb1d2873d16b63f2',
    messagingSenderId: '366242787575',
    projectId: 'caretutors-notes-app',
    storageBucket: 'caretutors-notes-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuE-yXjULc3ewt4k4MDcd-BpOsYr36_FU',
    appId: '1:366242787575:ios:e81b7bf1e4c9bbc56b63f2',
    messagingSenderId: '366242787575',
    projectId: 'caretutors-notes-app',
    storageBucket: 'caretutors-notes-app.firebasestorage.app',
    iosBundleId: 'com.example.caretutorsNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuE-yXjULc3ewt4k4MDcd-BpOsYr36_FU',
    appId: '1:366242787575:ios:e81b7bf1e4c9bbc56b63f2',
    messagingSenderId: '366242787575',
    projectId: 'caretutors-notes-app',
    storageBucket: 'caretutors-notes-app.firebasestorage.app',
    iosBundleId: 'com.example.caretutorsNotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZz-DtWflxkF5w85Ij8JlTyriS_FICi44',
    appId: '1:366242787575:web:a90edc1219ad331f6b63f2',
    messagingSenderId: '366242787575',
    projectId: 'caretutors-notes-app',
    authDomain: 'caretutors-notes-app.firebaseapp.com',
    storageBucket: 'caretutors-notes-app.firebasestorage.app',
    measurementId: 'G-VMC5V6VXZ0',
  );
}
